"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.testAsyncErrorEmail = exports.testErrorEmail = void 0;
/**
 * Utilitaire pour tester l'envoi d'emails sur les erreurs non rattrap√©es
 *
 * Pour l'utiliser:
 * 1. Importez cette fonction dans le fichier de votre choix
 * 2. Appelez-la avec le d√©lai souhait√© (en ms)
 *
 * Exemple:
 * ```
 * import { testErrorEmail } from './utils/testErrorEmail';
 *
 * // Dans votre code
 * testErrorEmail(5000); // D√©clenchera une erreur apr√®s 5 secondes
 * ```
 */
const testErrorEmail = (delayMs = 3000) => {
    console.log(`üß™ Test d'erreur programm√© dans ${delayMs}ms...`);
    setTimeout(() => {
        try {
            // Simuler une erreur de r√©f√©rence - un type d'erreur non rattrap√©e commun
            // @ts-ignore - Cette ligne g√©n√®re intentionnellement une erreur
            const nonExistentVariable = undefinedVariable.someProperty;
        }
        catch (error) {
            // Pour tester unhandledRejection, on rejette une promesse sans la g√©rer
            Promise.reject(new Error("Test d'erreur de promesse non g√©r√©e"));
            // Pour tester uncaughtException, on lance une erreur en dehors d'un try/catch
            throw new Error("Test d'erreur non rattrap√©e pour l'envoi d'email");
        }
    }, delayMs);
};
exports.testErrorEmail = testErrorEmail;
/**
 * Test d'erreur asynchrone (pour tester unhandledRejection)
 */
const testAsyncErrorEmail = (...args_1) => __awaiter(void 0, [...args_1], void 0, function* (delayMs = 3000) {
    console.log(`üß™ Test d'erreur asynchrone programm√© dans ${delayMs}ms...`);
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            reject(new Error("Test d'erreur de promesse rejet√©e"));
        }, delayMs);
    });
});
exports.testAsyncErrorEmail = testAsyncErrorEmail;
